### ISSUE TITLE
Problem running the command: npm run start

### ISSUE THREAD

**Issue by kiko333** [energywebfoundation/switchboard-dapp#165]
aster
> ng serve

Job name "..getProjectMetadata" does not exist.
Error: Job name "..getProjectMetadata" does not exist.
    at Observable._subscribe (/home/pi/ew/switchboard-dapp-master/node_modules/@angular-devkit/architect/node_modules/@angular-devkit/core/src/experimental/jobs/simple-scheduler.js:350:23)
    at Observable._trySubscribe (/home/pi/ew/switchboard-dapp-master/node_modules/rxjs/internal/Observable.js:44:25)

, have you some tips, Thank very much

**Comment by kim-energyweb** [comment]
@kiko333 Could you please provide which Node Version you are using? Thank you.

**Comment by kiko333** [comment]
Hi, thank you Kim, now is working. I am deploy in raspberry 4 I was trying into versión 3 but  it is not working because the stack is not enough big.

Kind Regards, fran

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: kim-energyweb<mailto:notifications@github.com>
Enviado: domingo, 7 de febrero de 2021 17:22
Para: energywebfoundation/switchboard-dapp<mailto:switchboard-dapp@noreply.github.com>
CC: kiko333<mailto:ecotrust_123@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [energywebfoundation/switchboard-dapp] Problem running the command: npm run start (#165)


@kiko333<https://github.com/kiko333> Could you please provide which Node Version you are using? Thank you.

**Comment by kim-energyweb** [comment]
Hello Fran,

Good to know that it is already working on your end.
We will close this ticket.

Thank you.

Regards,
Kim
