### ISSUE TITLE
Unable to approve a DID for a new role

### ISSUE THREAD

**Issue by jreedy-riis** [energywebfoundation/switchboard-dapp#702]
On switchboard, I have users with pending requests to become a role. However, once a user (who is allowed to approve people into the role) approves them, the following error is show. This also occurs when trying to create a new VC to automatically issue a claim to a DID.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/87768696/182399088-3f875502-261f-4851-8b22-61d3c920f930.png">
<img width="567" alt="image" src="https://user-images.githubusercontent.com/87768696/182399178-723f63e9-ad06-41c3-b977-168f119662bc.png">

**Comment by jrhender** [comment]
Hi @jreedy-riis , thanks for taking the time to report the bug. Could you share the full namespace of the role that you are trying to issue? For example, `role1.roles.myapps.apps.myorg.iam.ewc`

**Comment by jreedy-riis** [comment]
I believe this bug has happened with all of my roles, but these namespaces for sure have had the bug:`installer.roles.newtestorg.iam.ewc` and `testbreakingrole.roles.newtestorg.iam.ewc`. Thanks!

**Comment by jreedy-riis** [comment]
In addition, (not sure if the right spot), I also experienced the same error when using the `[6.0.0-alpha.45](https://www.npmjs.com/package/iam-client-lib/v/6.0.0-alpha.45)` version of the `iam-client-lib` when trying to use the claimsService.issueClaim() function, however that function works correctly on `[5.0.2](https://www.npmjs.com/package/iam-client-lib/v/5.0.2)`. In addition, when using version `5.0.2` of the iam-client-lib, `publishPublicClaim` does not work correctly. While on version `6.0.0-alpha.45`, `publishPublicClaim` works as expected. If this is not the correct location for this, I can move this to the iam-client-lib repository.

**Comment by jreedy-riis** [comment]
Hello @jrhender, has there been any updates on this? I did just notice as well that I **do not** get the error when approving roles that use a DID as the issuer and revoker, however every role that uses a role as the approver or revoker gets the same "startsWith" error.

**Comment by jrhender** [comment]
@jreedy-riis no update yet but we will be taking a deeper look at it today. Thank you for your additional observation regarding the DID issuer/revoker vs the role approver and revoker

**Comment by JGiter** [comment]
Hi @jreedy-riis. We fixed several related bugs. Could you please check if your issue is still actual?

**Comment by jreedy-riis** [comment]
Hi @JGiter , I just checked and I am still getting the same issue. Thanks.

**Comment by JGiter** [comment]
@jreedy-riis Could you issue `admin.roles.newtestorg.iam.ewc` to `did:ethr:volta:0xc56e...`?

**Comment by jreedy-riis** [comment]
@JGiter I issued it, thanks!

**Comment by jreedy-riis** [comment]
I think I figured out why it was not working. The admin roles (and all other roles) were created with version 5 of the iam-client-lib. I created a completely new organization and roles on version 6 and approving works as expected.
