### ISSUE TITLE
Unable to approve a role with a role precondition

### ISSUE THREAD

**Issue by jreedy-riis** [energywebfoundation/switchboard-dapp#708]
In my app, `testdidproject.apps.newtestorg.iam.ewc`, I have to roles: `project-installer (project-installer.roles.testdidproject.apps.newtestorg.iam.ewc)` and `project-electrician (project-electrician.roles.testdidproject.apps.newtestorg.iam.ewc)`. To become the project-electrician, they must first have the org role `electrician.roles.newtestorg.iam.ewc` and the role of `project-installer` will approve them. However, the electrician is able to apply for enrollment on switchboard for the `project-electrician` role, but when the `project-installer` goes to approve them, it errors out and says "enrollment preconditon not met", even though the user has the org level role.

I also experience this issue when trying to approve the role through the iam-client-lib.

Electrician Org role definition:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/87768696/182710439-6e446cbf-a3ea-4fd3-87ea-e9272d918384.png">

Account with Electrician Org Role:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/87768696/182710248-3833a697-533c-4787-88ba-825fc3305d5b.png">

Account with Installer Org Role and Project-installer role:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/87768696/182710619-36a839cb-f5ae-418d-abe6-01b3a2552918.png">

Account with pending claim to approve:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/87768696/182710600-bf4e955a-47d8-4d0e-9ad3-77982efa0d5a.png">

Project-Electrician Precondition:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/87768696/182710710-44cc7216-8e25-435d-b2e9-e81c4886db78.png">

Error:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/87768696/182710916-f69e583a-b27d-4e74-bb18-772fb33a42bf.png">

**Comment by jrhender** [comment]
@jreedy-riis thank you for logging the bug. From your screenshots and the role configuration, it looks to me like you have done everything correctly. We will try to reproduce and get back to you shortly.

**Comment by jrhender** [comment]
@jreedy-riis we have been able to reproduce this and are determining how to fix. Will let you know when we have fix planned and target fix date.

**Comment by jreedy-riis** [comment]
Great thanks!

**Comment by whitneypurdum** [comment]
Hi @jreedy-riis, the fix for this should be available now. Thank you for reporting this. Let me know here if you are still unable to approve this role.

**Comment by jreedy-riis** [comment]
Thank you! I don't think I am getting this error anymore, however, I received the error described in https://github.com/energywebfoundation/switchboard-dapp/issues/702

**Comment by whitneypurdum** [comment]
> Thank you! I don't think I am getting this error anymore, however, I received the error described in #702

@jreedy-riis Thanks for letting me know, I will circle back on this!
