### ISSUE TITLE
Unable to approve an off-chain role

### ISSUE THREAD

**Issue by jreedy-riis** [energywebfoundation/switchboard-dapp#715]
Hello, in switchboard when I attempt to approve a role that has the registration types of on-chain and off-chain, I receive the following error. I also receive the same error through the `iam-client-lib`. I believe it is related to Infura deprecating their public IPFS gateway and they now require a dedicated sub-domain (https://docs.infura.io/infura/networks/ipfs/how-to/access-ipfs-content/public-gateway). 

![image](https://user-images.githubusercontent.com/87768696/184001340-13cb1522-01b7-4e8c-a27a-63e7e8f56501.png)
![image](https://user-images.githubusercontent.com/87768696/184001587-03849410-f4c8-46cf-8237-9cff73cee257.png)

**Comment by jrhender** [comment]
Hi @jreedy-riis , thanks for reporting. We're working on an urgent fix for this.

**Comment by jrhender** [comment]
Hi @jreedy-riis, this should now be resolved

**Comment by jreedy-riis** [comment]
Awesome thanks!
