### ISSUE TITLE
Unable to approve any roles that use Role Issuers or Revokers: 403 Forbidden

### ISSUE THREAD

**Issue by jreedy-riis** [energywebfoundation/switchboard-dapp#728]
I have two sub-org level roles `installer.roles.testsuborg.globalrenewables.iam.ewc` and `admin.roles.testsuborg.globalrenewables.iam.ewc` (however this bug appears on org level roles as well). The approver and revoker of the `installer` role is the `admin.roles.testsuborg.globalrenewables.iam.ewc`. As a new user, I enrolled into the `installer` role. After signing back into the `admin` wallet address, I am able to view the `installer` enrollment request. I am able to reject these freely, however, when I go to accept. I get a `403 forbidden error`. From the network requests,  `https://identitycache-dev.energyweb.org/v1/status-list/entries` is returning 
```
{"statusCode":403,"message":"did:ethr:volta:0x224cba4ae8d27ba69793cfefe042682b81ea77c5 is not allowed to issue switchboardrole.roles.testsuborg.globalrenewables.iam.ewc","error":"Forbidden"}
```

However, that DID is an approved (and published) admin account. However, enrolling/approving the admin (with a DID approver / revoker) works fine.

<img width="1720" alt="image" src="https://user-images.githubusercontent.com/87768696/184431326-12cb4cca-dfe3-4d4b-bf83-7122bd0210ab.png">
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/87768696/184431616-8f8aa4a1-13ea-4f1d-be57-36f4e6709593.png">
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/87768696/184431639-f1c51482-0a62-4932-bf0d-41a5f5c8e361.png">
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/87768696/184431666-43e14fbd-2806-41b6-8216-96e40bfc70d3.png">
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/87768696/184431730-2b9c2d93-46ec-4977-9354-544f5efc2f07.png">

**Comment by jrhender** [comment]
Thanks for logging @jreedy-riis . We will investigate. It seems to me like it could be related to the other issue you logged https://github.com/energywebfoundation/switchboard-dapp/issues/702, at least in the sense that is affect roles which have another role as issuer/revoker.

**Comment by JGiter** [comment]
Hi @jreedy-riis I beleive this bug should be fixed now. Could you please confirm that?

**Comment by jreedy-riis** [comment]
Its fixed, thank you!
