### ISSUE TITLE
Unable to create an organization (https://switchboard.energyweb.org/)

### ISSUE THREAD

**Issue by jreedy-riis** [energywebfoundation/switchboard-dapp#781]
### Description
Hello, I tried to create an organization on `https://switchboard.energyweb.org/`, however, I was unable too as got his error every time I clicked `create organization`
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/87768696/192333884-4cb2c337-479d-465b-92e5-00e1855a9306.png">

**Comment by jrhender** [comment]
Hi @jreedy-riis , please send me an email at john.henderson@energyweb.org and we can discuss how to proceed here
