### ISSUE TITLE
Registering an Asset

### ISSUE THREAD

**Issue by jreedy-riis** [energywebfoundation/switchboard-dapp#821]
# Description
Hello, recently I tried to register an asset to the volta test network. it looks like it goes through successfully, however, I am unable to view my registered assets in switchboard. Subsequently, when using the `iam-client-lib`, I try to create a role claim request for the asset, I receive a `403` error saying the DID does not have authorization to create the role claim request for the asset. The `iam-client-lib` version is `7.0.0-alpha.3`. Thanks!

# Image
<img width="1722" alt="Screen Shot 2022-11-29 at 1 32 32 PM" src="https://user-images.githubusercontent.com/87768696/204616597-14d0bedf-8d20-4e9e-80d5-384c1b89a56d.png">

**Comment by nichonien** [comment]
@jreedy-riis The issue is known to us and we are working on it and will try to resolve ASAP. This issue occurred with the last update of `SSI-Hub` as we have updated the `Asset` contract to be `UUPS` upgradeable proxy contract. 

We will let you know once this is resolve.

**Comment by nichonien** [comment]
@jreedy-riis We did a hotfix and it should work for you now.

**Comment by jreedy-riis** [comment]
Thanks for the quick response! I am still unable to view assets on `switchboard-dev`. I see that the hotfix was only applied to switchboard so I understand why my role assignment through the `iam-client-lib` may still not work.

**Comment by nichonien** [comment]
@jreedy-riis Since the `Assetmanager` contract has been updated, you will not be able to view / access the old assets. The `asset` functionality should work fine for new assets.

The same changes will be made to `iam-client-lib` i.e. to use the new deployed contract.

**Comment by jreedy-riis** [comment]
Okay thank you!
